### ISSUE TITLE
Save => Save Local  error : local api it is not yet loaded - please try again after loading

### ISSUE THREAD

**Issue by Saifulgani** [ignatandrei/NETCoreBlockly#157]
Hi Andrei,
Save => Save Local is displaying error: local api it is not yet loaded - please try again after loading

same error is displayed even in the demo site https://ignatandrei.github.io/BlocklyAutomation/automation/main

I am assuming Save => Save Local would save a file on local disk which can be loaded later. Instead the above error is displayed.
Am I missing something?

Btw, great work/project, thanks a ton!

Thanks,
Saif.

**Comment by ignatandrei** [comment]
I will verify ASAP ;-)  
Thanks for reporting

**Comment by ignatandrei** [comment]
I think that it not occur anymore with latest version
