### ISSUE TITLE
Where is Save Local data?

### ISSUE THREAD

**Issue by djaus2** [ignatandrei/NETCoreBlockly#158]
Where is Save Local data saved. Windows context.

**Comment by ignatandrei** [comment]
Save local will save to cookies.

**Comment by djaus2** [comment]
This then becomes a request to be able to save to a local drive or even some XML,say, that can be copied and reloaded.

**Comment by ignatandrei** [comment]
Could you please integrate blockly nuget   ? And then I will make a PR in order to show how to save/load on local ;-)

**Comment by djaus2** [comment]
I am using the Nuget version already. I see that what I want is already there:

Save to local file : **LOAD BLOCKS**>Download Blocks
Relaod:                 **LOAD BLOCKS**->Load Blocks

Thx

**Comment by ignatandrei** [comment]
Sorry , I will review ASAP the repo ( plenty of work at work ;-) )

**Comment by djaus2** [comment]
@ignatandrei 
All good now. Have created a number of Softata samples and saved in repository in  SoftaWebAPI/Samples folder:
[djaus2//SoftataWebAPI/Samples](https://github.com/djaus2/Soft-ata/tree/master/SoftataWebAPI/Samples)

Closing this issue
