### ISSUE TITLE
Can override Host/Port be removed from a Custom API?

### ISSUE THREAD

**Issue by djaus2** [ignatandrei/NETCoreBlockly#159]
I have MySite->API->Custom APIs
These are  implemented as Controllers in a WebAPI

Can the control be optionally changed to remove the clutter of having **override Host** and **override Port**?
![image](https://github.com/ignatandrei/NETCoreBlockly/assets/12537105/9d7f7140-272a-48e6-b4c2-9c35d33cd0df)

**Comment by ignatandrei** [comment]
It was meant to can call same API on different servers. But yes, you are right. I will think and modify

**Comment by djaus2** [comment]
I am working on a .NET to Arduino orchestrator.
https://github.com/djaus2/Soft-ata
My ultimate goal is to orchestrate from something like Blockly which I now have just achieved.
David Jones (Microsoft MVP)


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by djaus2** [comment]
I have written a blog post for my context wrt NETCore Blockly:
DjsBlog: Softata -Blockly ... The Holy Grail (windows.net)<https://djzblogaccname137.z26.web.core.windows.net/softata/Softata-Blockly____The_Holy_Grail-softata.html>

David Jones

**Comment by ignatandrei** [comment]
I do not see a reference to NETCoreBlockly . I can instrument for you in a PR , if you want

**Comment by djaus2** [comment]
Re: The Repository. Have fixed that now. I had removed Meadow/NetStandrd from the repository because of a bug. I have recently revisted it but didn't reinclude it in the repository. Note that the Meadow code has a documented bug so isn't usable at this moment. Awaiting a submitted bug fix.

**Comment by ignatandrei** [comment]
https://github.com/djaus2/Soft-ata/pull/4 - adding to show how to put Soft-Ata API at startup and examples

**Comment by djaus2** [comment]
Thanks to @ignatandrei  Softata Samples are now directly available as Examples in Blockly.

**Comment by djaus2** [comment]
Thanks for you help with this.
Looking good.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ignatandrei** [comment]
It will be ready in the next version

**Comment by ignatandrei** [comment]
Update latest [nuget.org/packages/NetCore2Blockly](https://www.nuget.org/packages/NetCore2Blockly) version 8.2024.503.745

**Comment by djaus2** [comment]
Great! Thats works. Thanks.
![image](https://github.com/ignatandrei/NETCoreBlockly/assets/12537105/d745d500-9eee-4c68-9a69-3fce7575ca44)

:)
