### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by djaus2** [ignatandrei/NETCoreBlockly#160]
None of these are blocking issues

1. Adding comments as blocks within code. No functuionality though.  ***Workaraound:*** Provide as a simple Print block.
2. C style opertaors on numerical variables  eg Set Block can have a ++ ,-- , * and / etc connected to it.

**Comment by djaus2** [comment]
**_Two More Suggestions, both non-urgent_**

Just implemented a function where some reuse of code stood out.
Q Are functiont documented ib detail anywhere. Had to be a bit of expirementing to get it to work but know how to do ,
I will post my example later in my Softata examples.

3. Can we have a library of fucntions where the blocks are saved to a file and loaded into the current progarm.
Better still if these fucntions/library were implicitly loaded as one smnall block or some otherhidden manner.

4. **Or** can we have tabs where fucntion blocks can be separately loaded and saved.

**_PS The creation of my examples has been quite easy once I had created my API._** :)

**Comment by ignatandrei** [comment]
Q: Are functiont documented ib detail anywhere.
A: No , the functions are not documented. Yes, I'd wish to do so . But for the moment, I am one man show ;-)

Q: Can we have a library of fucntions where the blocks are saved to a file and loaded into the current progarm.
A: I see that you have put your things into the "Examples ! " button  
"SoftataWebAPI\wwwroot\BlocklyAutomation\assets\showUsage\demoBlocks"
I assume that you are refering to something else, that I do not understand ? 

Q: "Or can we have tabs where fucntion blocks can be separately loaded and saved."
A:  Are you referring to something like macros , a composition of multiple functions ? 

Q: "Bit manipulation SHL SHR AND XOR etc."
A: I do not know if this exists in Javascript .... I will see .

**Comment by djaus2** [comment]
I have posted an teh example usinga function here [ github.com Soft-ata SoftataWebAPI Neopixel8-Display-Fuctional-Example-pin-16.txt](https://github.com/djaus2/Soft-ata/blob/master/SoftataWebAPI/wwwroot/BlocklyAutomation/assets/showUsage/demoBlocks/Neopixel8-Display-Fuctional-Example-pin-16.txt)

**Comment by djaus2** [comment]
Re 2. From first comment here.
Change ... By ...  can be used as ++ -- :)
Perhaps that could be extended for other operations?

**Comment by djaus2** [comment]
Re 2. Again
I see much of ythis functionality is now available in other  Tab    set ... op ...
:)

**Comment by ignatandrei** [comment]
I will try to make this weekend ( and also upgrade Blockly to latest version)

**Comment by djaus2** [comment]
<img width="286" alt="image" src="https://github.com/ignatandrei/NETCoreBlockly/assets/12537105/b1ba22f0-7ec0-439a-bd94-0c33f979bc12">

Just implemented a test block app as above. :)

**Comment by ignatandrei** [comment]
I have updated blockly to the latest version (10.4.3)  - so please update your project to .net 8 and
```xml
    <PackageReference Include="NetCore2Blockly" Version="8.2024.428.1000" />
```

 Now I can make all modifications without fear 

I suggest that we close those thread and open another with modifications needed.

**Comment by djaus2** [comment]
OK thanks.
Have successfully upgraded.

**Comment by djaus2** [comment]
will repost some of my suggestions as separate items, given this is now closed
