### ISSUE TITLE
Incode Comments

### ISSUE THREAD

**Issue by djaus2** [ignatandrei/NETCoreBlockly#162]
Adding comments as blocks within code. No functionality though. 
> Workaround: Implement as a simple Print block

**Comment by ignatandrei** [comment]
It will be ready in the next release

**Comment by ignatandrei** [comment]
Update latest  https://www.nuget.org/packages/NetCore2Blockly version 8.2024.503.745

You will find an example https://ignatandrei.github.io/BlocklyAutomation/automation/loadexample/comments

![image](https://github.com/ignatandrei/NETCoreBlockly/assets/153982/9c17e39e-360f-483b-8e5a-8fc7eb0d6d59)

**Comment by djaus2** [comment]
Great. **comment** works nicely! :)

How do you use the **debugger** block?
Tried it and get : 
```
ReferenceError: startDebugger is not defined
```

Great work on your part!

**Comment by ignatandrei** [comment]
I will review the debugger ASAP

**Comment by ignatandrei** [comment]
The debugger is for the console of the web browser - and , indeed ,it is an error. It will be in the next version
