### ISSUE TITLE
Library of Blockly functions

### ISSUE THREAD

**Issue by djaus2** [ignatandrei/NETCoreBlockly#163]
Can we have a mechanism of saving a set of Blockly functions separate from the app so that they can reloaded into another app as a single entity.?
eg
- As a separate page
- As a single  block( or one for reach function) on the app page .

**Comment by ignatandrei** [comment]
I will make an example with custom categories ASAP

**Comment by ignatandrei** [comment]
Update latest [nuget.org/packages/NetCore2Blockly](https://www.nuget.org/packages/NetCore2Blockly) version 8.2024.503.745

Put a file named customCategories.txt

```xml
<category name='CategoriesLoaded'>
</category>
```

and inside put your blocks

![image](https://github.com/ignatandrei/NETCoreBlockly/assets/153982/83826e2a-4df5-451f-99f8-cddeeb3622e5)

**Comment by djaus2** [comment]
OK so have created app with simple function:
![image](https://github.com/ignatandrei/NETCoreBlockly/assets/12537105/7557bbb1-3ecf-48a9-83f3-0135985498d1)

Downloaded that and extracted the function part of it:
```xml
  <block type="procedures_defnoreturn" x="107" y="488">
  ...
  ...
  </block>
```

I created a file in Downloads directory where DownloadBlocks saves to, called customCategories.txt. With the block code in it:

```xml
<category name='CategoriesLoaded'>
  <block type="procedures_defnoreturn" x="107" y="488">
    <field name="NAME">GetData</field>
    <comment pinned="false" h="80" w="160">Print current Date-Time</comment>
    <statement name="STACK">
      <block type="text_print">
        <value name="TEXT">
          <block type="displayCurrentDate">
            <field name="dateFormat">human</field>
          </block>
        </value>
      </block>
    </statement>
  </block>
</category>
```

The "Category" isn't being loaded. ???

**Comment by ignatandrei** [comment]
Sorry for not being clear
Then folder  for the file is assets\loadAtStartup

For your case , make a folder named loadAtStartup  in SoftataWebAPI\wwwroot\BlocklyAutomation\assets 
and put there the file

**Comment by djaus2** [comment]
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by djaus2** [comment]
Thanks that all worked. :)

- Using version 8.2024.503.745
- Created folder 

```
SoftataWebAPI\wwwroot\BlocklyAutomation\assets\loadAtStartup
```

- Created text file in that folder called:

```
customCategories.txt
```

- Made sure it was being copied to the built output
- Inserted code as previous ***(WITHOUT the XML monikers)***!
- Ran Blockly and could access any functions in that file via **CategoriesLoaded**. 
- Functions then available under Basic-->Functions
- Functions renamed if already existing
- Can then reuse functions. 

All good now, thanks again. :)

**Comment by djaus2** [comment]
All good now, thanks again. :)
