### ISSUE TITLE
Given an enum type as parameter to a Controller can the enum literals show rather than the ordinal?

### ISSUE THREAD

**Issue by djaus2** [ignatandrei/NETCoreBlockly#172]
I have a setup controller that takes an index idisplay which determines the display to be setup:

```cs
        [Route("SetupDefault")]
        [HttpPost] // Default setup for display
        public IActionResult SetupDefault(int idisplay=0)
        {
	} 
```  

The displays are defined as an enum: 

```cs
public enum DisplayDevice : byte { OLED096, LCD1602, NEOPIXEL,BARGRAPH,GBARGRAPH, /* Add Here, */ Undefined = 0xFF }
```    

So if I add a controller thus:

```cs
        [Route("SetupDefaultfromList")]
        [HttpPost] // Default setup for display from list
        public IActionResult SetupDefaultfromList(DisplayDevice idisplay )
        {
		...
	}
```

The DisplayDevice object is now available and can be slotted into a SetupDefaultfromList block.
This make it a simple menu. 

But what is displayed is the ordinal values not the enum literals.

Is there a way to do this like DayOfTheWeek and Operation in the examples?
That is ,**given an enum type as parameter to a Controller can the enum literals show rather than the ordinal?**

**Comment by djaus2** [comment]
Have added a description to each value such as:
```cs
 [Description("First Value")]
    Value1,
```

**Comment by ignatandrei** [comment]
How it is displayed in swagger?   What kind of swagger library do you use ?

You may use also 

```csharp
builder.Services.AddControllers().AddJsonOptions(options =>
 options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
```

**Comment by djaus2** [comment]
Before adding that code::
![image](https://github.com/user-attachments/assets/681e120b-7610-4b98-a7ea-e1003f06c000)

After adding that code:
![image](https://github.com/user-attachments/assets/25ccfbfd-b9f7-4c04-bef3-f0e6d8d1c244)

That worked, thanks.
See next

**Comment by djaus2** [comment]
![image](https://github.com/user-attachments/assets/41abb4c7-1607-46e7-97e8-c5a8798f6c5b)

Output:

![image](https://github.com/user-attachments/assets/9a606bfc-d184-4379-95ff-7d4e1aabccf8)

:)

**Comment by djaus2** [comment]
Thx again for your quick resposne Andrei!

**Comment by djaus2** [comment]
Thx again for your quick resposne Andrei!
