### ISSUE TITLE
graphql

### ISSUE THREAD

**Issue by ignatandrei** [ignatandrei/NETCoreBlockly#19]
Add graphql

**Comment by ignatandrei** [comment]
Generate blocks from a graphql definition.

**Comment by ignatandrei** [comment]
Example form graphql with EF :
https://visualstudiomagazine.com/articles/2020/01/28/graphql-data-retrieval.aspx
( we have alread an SqlServer in memory with Deparments and employee)

**Comment by ignatandrei** [comment]
https://visualstudiomagazine.com/articles/2020/05/04/flexible-graphql-queries.aspx

**Comment by ignatandrei** [comment]
see also https://github.com/graphql/graphiql

**Comment by cosminpopescu14** [comment]
https://developer.okta.com/blog/2019/04/16/graphql-api-with-aspnetcore

**Comment by ignatandrei** [comment]
There is already a database context in the project to be used: 

services.AddDbContext<testsContext>(options => options

**Comment by cosminpopescu14** [comment]
https://github.com/cosminpopescu14/NETCoreBlockly/tree/feature/graphql

**Comment by cosminpopescu14** [comment]
1. Ce obeicte si tipuri am in schema
 var typesKindName = @"{
                                      __schema {
                                        types {
                                          name kind
                                        }
                                      }
                                    }";

2. Iterare in obiectele astea cu kindObject si trimiti {
  __type(name: "ObiectulMeuOGT") {
    name
    fields {
      name
      type {
        name
        kind
      }
    }
  }
}
3 creezi pt ObiectulMeuOGT cate un GraphQLTypeArgument cu nume si propeietati care sunt filed-urile

**Comment by ignatandrei** [comment]
https://graphql-dotnet.github.io/docs/getting-started/arguments/

**Comment by ignatandrei** [comment]
Step 1; Intrebi de 
{
  __schema {
    queryType {
      name kind
    }
  }
}

Step 2.
Cu name , iei obiectul si field-urile ( astea vor fi actiunile)

Step 3
Pentru fiecare field, iei sub obiectele si le pui in clase

**Comment by cosminpopescu14** [comment]
{
               "kind":"OBJECT",
               "name":"GetAllQuery",
               "description":null,
               "fields":[
                  {
                     "name":"departmentQuery",
                     "description":null,
                     "args":[

                     ],
                     "type":{
                        "kind":"LIST",
                        "name":null,
                        "ofType":{
                           "kind":"OBJECT",
                           "name":"DepartmentOGT",
                           "ofType":null
                        }
                     },
                     "isDeprecated":false,
                     "deprecationReason":null
                  },
                  {
                     "name":"employeeQuery",
                     "description":null,
                     "args":[

                     ],
                     "type":{
                        "kind":"LIST",
                        "name":null,
                        "ofType":{
                           "kind":"OBJECT",
                           "name":"EmployeeOGT",
                           "ofType":null
                        }
                     },
                     "isDeprecated":false,
                     "deprecationReason":null
                  },
                  {
                     "name":"getOneDepartment",
                     "description":null,
                     "args":[
                        {
                           "name":"id",
                           "description":null,
                           "type":{
                              "kind":"SCALAR",
                              "name":"ID",
                              "ofType":null
                           },
                           "defaultValue":"null"
                        }
                     ],
                     "type":{
                        "kind":"OBJECT",
                        "name":"DepartmentOGT",
                        "ofType":null
                     },
                     "isDeprecated":false,
                     "deprecationReason":null
                  }
               ],
               "inputFields":null,
               "interfaces":[

               ],
               "enumValues":null,
               "possibleTypes":null
            }

**Comment by cosminpopescu14** [comment]
https://i.kym-cdn.com/entries/icons/original/000/028/021/work.jpg

**Comment by cosminpopescu14** [comment]
Implemented
