### ISSUE TITLE
add generic host for each HTTP block (vary by host) to add credentials

### ISSUE THREAD

**Issue by ignatandrei** [ignatandrei/NETCoreBlockly#38]
add generic host for each HTTP block (vary by host) to add credentials
For example, some credentials might be transmitted via Header (JWT)

**Comment by ignatandrei** [comment]
as a test , https://api.chucknorris.io/

**Comment by robertszabobv** [comment]
Using Postman
- to get the bearer token, send a POST request to api/registration. The body of this request should contain "blockly"
- to test authorization, send a GET request to api/restrictedaccess. This request needs to have an Authorization header set to Bearer <token>
- sending GET request to api/restrictedaccess without the Authorization token will generate a 401 unauthorized response

**Comment by ignatandrei** [comment]
done -see JWT  on https://netcoreblockly.herokuapp.com/blockly.html
