### ISSUE TITLE
date time block output

### ISSUE THREAD

**Issue by ignatandrei** [ignatandrei/NETCoreBlockly#63]
the current date should have a dropdown block w- what to display
ISO 8601 -  2020-05-04T06:02:57Z , https://en.wikipedia.org/wiki/ISO_8601
Locale
Unix

**Comment by cosminpopescu14** [comment]
branch here
https://github.com/cosminpopescu14/NETCoreBlockly/tree/feature/date-time-block-output

There are some errors. I will correct them
